### ISSUE TITLE
Milestone 3: Query Layer Implementation

### ISSUE THREAD

**Issue by gnumonik** [mlabs-haskell/DeNS#25]
@jaredponn  I *think* that given our design, this requires the Arweave stuff to be in place. The milestone says: 

"Acceptance criteria: The aforementioned package is able to populate a relational database of DNS records by querying/indexing testnet transactions." 

Let's try to break this down into a set of sub-issues to track progress better. 

[Link to milestone](https://milestones.projectcatalyst.io/projects/1000120/milestones/3)

**Comment by jaredponn** [comment]
Following our Slack discussion, let's change the scope of this a bit so it doesn't need Arweave. 

We'll store the records inline for this milestone, and move the Arweave work to milestone 4.
